// Generated by Selenium IDE
package org.example;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

public class AuthorizationTest {
  private WebDriver driver;

  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "geckodriver.exe");
    driver = new FirefoxDriver();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void authorization() {
    driver.get("https://diary.ru/");
    driver.manage().window().maximize();
    driver.findElement(By.xpath("//a[@href='https://diary.ru/user/login']")).click();
    driver.findElement(By.id("loginform-username")).click();
    driver.findElement(By.id("loginform-username")).sendKeys("sissergey");
    driver.findElement(By.id("loginform-password")).click();
    driver.findElement(By.id("loginform-password")).sendKeys("63623400");
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();
    new WebDriverWait(driver, 30);
    driver.switchTo().defaultContent();
    driver.findElement(By.id("login_btn")).click();
  }
}
