// Generated by Selenium IDE
package org.example;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateNewUserTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createnewuser() {
    driver.get("https://diary.ru/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.linkText("Регистрация")).click();
    driver.findElement(By.id("signupform-username")).click();
    driver.findElement(By.id("signupform-username")).sendKeys("sissergey");
    driver.findElement(By.id("signupform-password")).click();
    driver.findElement(By.id("signupform-password")).sendKeys("63623400");
    driver.findElement(By.id("signupform-email")).click();
    driver.findElement(By.id("signupform-email")).sendKeys("sissergey@yandex.by");
    driver.findElement(By.id("chk_box_user_confirm")).click();
    driver.findElement(By.id("signup_btn")).click();
    driver.findElement(By.id("newblogform-title")).click();
    driver.findElement(By.id("newblogform-title")).sendKeys("Мой дневник");
    driver.findElement(By.name("new-blogs-button")).click();
    driver.findElement(By.id("post0")).click();
    driver.findElement(By.id("epigraph")).click();
  }
}
